export const FETCH_RECIPES_REQUEST = 'FETCH_RECIPES_REQUEST'
export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS'
export const FETCH_RECIPES_FAILURE = 'FETCH_RECIPES_FAILURE'

export const POST_RECIPES_REQUEST = 'POST_RECIPES_REQUEST'
export const POST_RECIPES_SUCCESS = 'POST_RECIPES_SUCCESS'
export const POST_RECIPES_FAILURE = 'POST_RECIPES_FAILURE'

export const RATE_RECIPE = 'RATE_RECIPE'
